name: dart_codes 
description: Nothing

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies: 
  lints: ^1.0.1
dependencies: 
  ansicolor: ^2.0.1
  dart_clipboard: ^0.3.0
  prompts: ^2.0.0
  randt: ^1.1.0
  